"""Transparent project/document model used by the E3 desktop application."""

from .model import (
    DEFAULT_LAYER_COLORS,
    PROJECT_SCHEMA_VERSION,
    Bounds,
    LayerMode,
    ObjectKind,
    OperationLayer,
    ProjectDocument,
    ProjectFormatError,
    SceneObject,
    Transform,
)
from .alignment import Alignment, aligned_transforms, distributed_transforms
from .history import (
    AddLayerCommand,
    AddObjectCommand,
    AddObjectsCommand,
    AssignLayerCommand,
    Command,
    CommandStack,
    DuplicateObjectsCommand,
    FunctionalCommand,
    GroupObjectsCommand,
    RemoveLayerCommand,
    ReorderLayersCommand,
    ReorderObjectsCommand,
    RemoveObjectsCommand,
    UngroupObjectsCommand,
    UpdateLayerCommand,
    UpdateObjectPropertiesCommand,
    UpdateObjectShapeCommand,
    UpdateTransformCommand,
    UpdateTransformsCommand,
)
from .io import (
    PROJECT_EXTENSION,
    autosave_is_newer,
    autosave_path,
    clear_autosave,
    load_project,
    normalize_project_path,
    save_autosave,
    save_project,
)
from .toolpath import ProjectJob, generate_project_frame, generate_project_gcode, object_polylines

__all__ = [
    "AddLayerCommand",
    "AddObjectCommand",
    "AddObjectsCommand",
    "Alignment",
    "AssignLayerCommand",
    "Bounds",
    "Command",
    "CommandStack",
    "DEFAULT_LAYER_COLORS",
    "DuplicateObjectsCommand",
    "FunctionalCommand",
    "GroupObjectsCommand",
    "LayerMode",
    "ObjectKind",
    "OperationLayer",
    "PROJECT_EXTENSION",
    "PROJECT_SCHEMA_VERSION",
    "ProjectDocument",
    "ProjectFormatError",
    "ProjectJob",
    "RemoveLayerCommand",
    "ReorderLayersCommand",
    "ReorderObjectsCommand",
    "RemoveObjectsCommand",
    "SceneObject",
    "Transform",
    "UngroupObjectsCommand",
    "UpdateLayerCommand",
    "UpdateObjectPropertiesCommand",
    "UpdateObjectShapeCommand",
    "UpdateTransformCommand",
    "UpdateTransformsCommand",
    "aligned_transforms",
    "autosave_is_newer",
    "autosave_path",
    "clear_autosave",
    "distributed_transforms",
    "generate_project_frame",
    "generate_project_gcode",
    "load_project",
    "normalize_project_path",
    "object_polylines",
    "save_autosave",
    "save_project",
]
