"""Shared bounded-work constants for project planning and advisory preflight."""

MAX_STREAM_COMMANDS = 250_000
MAX_RASTER_SAMPLES = 16_000_000
MAX_RASTER_ROWS = 60_000
MAX_SCANLINE_EDGE_TESTS = 16_000_000
STREAM_COMMAND_RESERVE = 64
MAX_NEAREST_ORDER_PATHS = 512
MAX_UNIQUE_RASTER_ASSETS = 64
MAX_UNIQUE_RASTER_ENCODED_BYTES = 64 * 1024 * 1024
MAX_UNIQUE_RASTER_DECODED_BYTES = 64 * 1024 * 1024


__all__ = [
    "MAX_NEAREST_ORDER_PATHS",
    "MAX_RASTER_ROWS",
    "MAX_RASTER_SAMPLES",
    "MAX_SCANLINE_EDGE_TESTS",
    "MAX_STREAM_COMMANDS",
    "MAX_UNIQUE_RASTER_ASSETS",
    "MAX_UNIQUE_RASTER_DECODED_BYTES",
    "MAX_UNIQUE_RASTER_ENCODED_BYTES",
    "STREAM_COMMAND_RESERVE",
]
